<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #333;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background-color: #f2f2f2;
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
            font-weight: bold;
        }
        td {
            border: 1px solid #ddd;
            padding: 8px;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            color: #666;
            font-size: 10px;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .date-range {
            margin: 10px 0;
            font-style: italic;
        }
        .summary {
            margin: 10px 0;
            padding: 10px;
            background-color: #f9f9f9;
            border-radius: 5px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>University Attendance System</p>
        <p><strong>Generated on:</strong> {{ \Carbon\Carbon::now('Asia/Colombo')->format('Y-m-d h:i:s A') }}</p>
        
        @if($startDate && $endDate)
            <div class="date-range">
                Period: {{ $startDate }} to {{ $endDate }}
            </div>
        @endif
        
        <div class="summary">
            Total Records: {{ $data->count() }}
        </div>
    </div>
    
    <table>
        <thead>
            <tr>
                <th>#</th>
                @foreach($columns as $column)
                    <th>{{ $column }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach($data as $index => $item)
            <tr>
                <td>{{ $index + 1 }}</td>
                
                @if($reportType === 'students')
                    <td>{{ $item->student_id }}</td>
                    <td>{{ $item->user->name }}</td>
                    <td>{{ $item->user->email }}</td>
                    <td>{{ $item->user->nic }}</td>
                    <td>{{ $item->phone }}</td>
                    <td>{{ $item->courses->count() }}</td>
                    <td>{{ $item->created_at->format('Y-m-d') }}</td>
                    
                @elseif($reportType === 'lecturers')
                    <td>{{ $item->employee_id }}</td>
                    <td>{{ $item->user->name }}</td>
                    <td>{{ $item->user->email }}</td>
                    <td>{{ $item->department }}</td>
                    <td>{{ $item->qualification }}</td>
                    <td>{{ $item->courses->count() }}</td>
                    
                @elseif($reportType === 'courses')
                    <td>{{ $item->course_code }}</td>
                    <td>{{ $item->course_name }}</td>
                    <td>{{ $item->lecturer->user->name ?? 'N/A' }}</td>
                    <td>{{ Str::limit($item->description, 50) }}</td>
                    <td>{{ $item->students->count() }}</td>
                    <td>{{ $item->created_at->format('Y-m-d') }}</td>
                    
                @elseif($reportType === 'attendance')
                    <td>{{ $item->student->user->name ?? 'N/A' }}</td>
                    <td>{{ $item->session->course->course_name ?? 'N/A' }}</td>
                    <td>{{ $item->session->title ?? 'N/A' }}</td>
                    <td>{{ $item->attended_at->format('Y-m-d H:i') }}</td>
                    <td>{{ $item->status }}</td>
                    <td>{{ $item->remarks }}</td>
                @endif
            </tr>
            @endforeach
            
            @if($data->isEmpty())
            <tr>
                <td colspan="{{ count($columns) + 1 }}" style="text-align: center; padding: 20px;">
                    No data found for this report.
                </td>
            </tr>
            @endif
        </tbody>
    </table>
    
    <div class="footer">
        <p>Page generated by University Attendance System</p>
        <p>© {{ date('Y') }} - All rights reserved</p>
    </div>
</body>
</html>